[project]
name = "uav-cyber-sim"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "empy==3.3.4",
    "folium",
    "geopy",
    "ipykernel",
    "ipython",
    "matplotlib",
    "nbformat",
    "numpy",
    "pandas",
    "plotly",
    "psutil",
    "pymap3d",
    "pymavlink",
    "pyserial",
    "pyzmq",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
extend-ignore = ["D205", "D212", "D107", "D105"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
ignore_missing_imports = true
