[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
extend-ignore = ["D205", "D212", "D107", "D105"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
ignore_missing_imports = true
