[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = true
known_first_party = [
    "plan",
    "simulators",
    "vehicle_logic",
    "proxy",
    "oracle",
    "config",
]

[tool.black]
line-length = 88
