"""Autogenerated. MAVLink codes for Plane flight mode."""

from __future__ import annotations

from enum import IntEnum


class PlaneMode(IntEnum):
    """
    Autogenerated. Autogenerated from PLANE_MODE entries starting with
    `PLANE_MODE_`.
    """

    ACRO = 4
    AUTO = 10
    AUTOLAND = 26
    AUTOTUNE = 8
    AVOID_ADSB = 14
    CIRCLE = 1
    CRUISE = 7
    ENUM_END = 27
    FLY_BY_WIRE_A = 5
    FLY_BY_WIRE_B = 6
    GUIDED = 15
    INITIALIZING = 16
    LOITER = 12
    LOITER_ALT_QLAND = 25
    MANUAL = 0
    QACRO = 23
    QAUTOTUNE = 22
    QHOVER = 18
    QLAND = 20
    QLOITER = 19
    QRTL = 21
    QSTABILIZE = 17
    RTL = 11
    STABILIZE = 2
    TAKEOFF = 13
    THERMAL = 24
    TRAINING = 3
