"""Autogenerated. ."""

from __future__ import annotations

from enum import IntEnum


class State(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_STATE entries starting with
    `MAV_STATE_`.
    """

    ACTIVE = 4
    BOOT = 1
    CALIBRATING = 2
    CRITICAL = 5
    EMERGENCY = 6
    ENUM_END = 9
    FLIGHT_TERMINATION = 8
    POWEROFF = 7
    STANDBY = 3
    UNINIT = 0
