"""
Generate Enum source file for ArduPilot parameter names as ByteEnum members.

Reads:
    simulator/helpers/ardupilot/ardupilot.pdef.json

Writes:
    simulator/helpers/ardupilot/enums/<name>.py  (one file per entry in PARAM_DEFS)
    simulator/helpers/ardupilot/enums/__init__.py (updated with all enum exports)

It is intended for occasional, developer-triggered use—typically after updating
ArduPilot parameter definitions—rather than regular execution.

Run from the repo root:

    python tools/gen_ardupilot_byteenum.py
"""

import importlib.util
import json
import os
import re

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(BASE_DIR)
_ARDUPILOT_HELPERS = os.path.join(_REPO_ROOT, "simulator", "helpers", "ardupilot")
_codegen_path = os.path.join(_REPO_ROOT, "simulator", "helpers", "codegen.py")
_spec = importlib.util.spec_from_file_location("codegen", _codegen_path)
assert _spec is not None and _spec.loader is not None
_codegen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_codegen)  # type: ignore[union-attr]
make_docstring = _codegen.make_docstring
write_init_file = _codegen.write_init_file


def _existing_enum_names(enums_dir: str) -> list[str]:
    """Parse class names from enums/__init__.py without importing the module."""
    init_path = os.path.join(enums_dir, "__init__.py")
    if not os.path.exists(init_path):
        return []
    with open(init_path) as f:
        return re.findall(r"^from \.\w+ import (\w+)", f.read(), re.MULTILINE)
PDEF_PATH = os.path.join(_ARDUPILOT_HELPERS, "ardupilot.pdef.json")
_PDEF_REL = os.path.relpath(PDEF_PATH, _REPO_ROOT)

with open(PDEF_PATH) as f:
    PDEF: dict[str, dict[str, object]] = json.load(f)

# Each entry defines one generated enum file:
#   key    — group key inside ardupilot.pdef.json
#   prefix — only params starting with this string are included;
#            also stripped from member names
#   name   — Python class name
#   doc    — one-line docstring
PARAM_DEFS: list[dict[str, str]] = [
    {
        "key": "WPNAV_",
        "prefix": "WPNAV_",
        "name": "WPNav",
        "doc": "ArduCopter waypoint navigation parameters.",
    },
    {
        "key": "Plane",
        "prefix": "AIRSPEED_",
        "name": "AirSpeed",
        "doc": "ArduPlane airspeed parameters.",
    },
]


def extract_param_values(key: str, prefix: str) -> list[str]:
    """Extract param names from group `key` that start with `prefix`."""
    return [k for k in PDEF[key] if k.startswith(prefix)]


def generate_param_enum(
    enum_name: str, docstring: str, param_names: list[str], key: str, prefix: str
) -> str:
    """Generate source code for a bytes-based Enum class."""
    lines = [
        make_docstring(docstring, indent=0),
        "",
        "from enum import Enum",
        "",
        "",
        f"class {enum_name}(bytes, Enum):",
        make_docstring(
            f"Autogenerated from `{key}` entries starting with `{prefix}` "
            f"in {_PDEF_REL}.",
            indent=4,
        ),
        "",
    ]
    for name in param_names:
        shortname = name.removeprefix(prefix)
        if shortname.isidentifier():
            lines.append(f'    {shortname} = b"{name}"')
        else:
            sanitized = shortname.replace("-", "_").replace(".", "_")
            lines.append(f'    {sanitized} = b"{name}"  # original name: {name}')
    return "\n".join(lines) + "\n"


def write_param_enum_file(
    name: str, doc: str, param_names: list[str], key: str, prefix: str, outfile: str
) -> None:
    """Write generated bytes-based Enum to file."""
    code = generate_param_enum(name, doc, param_names, key, prefix)
    os.makedirs(os.path.dirname(outfile), exist_ok=True)
    with open(outfile, "w") as f:
        f.write(code)
    print(f"✅ Param enum written to {outfile}")


if __name__ == "__main__":
    ENUM_DIR = os.path.join(_ARDUPILOT_HELPERS, "enums")
    for param in PARAM_DEFS:
        outfile = os.path.join(ENUM_DIR, f"{param['name'].lower()}.py")
        values = extract_param_values(param["key"], param["prefix"])
        write_param_enum_file(
            param["name"], param["doc"], values, param["key"], param["prefix"], outfile
        )
    generated = [e["name"] for e in PARAM_DEFS]
    write_init_file(ENUM_DIR, generated + _existing_enum_names(ENUM_DIR))
