"""
Generate Enum source file for ArduPilot-style parameter values as IntEnum members.

Reads:
    simulator/helpers/ardupilot/ardupilot.pdef.json

Writes:
    simulator/helpers/ardupilot/enums/<name>.py  (one file per entry in PARAM_DEFS)
    simulator/helpers/ardupilot/enums/__init__.py (updated with all enum exports)

It is intended for occasional, developer-triggered use—typically after updating
ArduPilot parameter definitions—rather than regular execution.

Run from the repo root:

    python tools/gen_intenum.py
"""

import importlib.util
import json
import os
import re

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(BASE_DIR)
_ARDUPILOT_HELPERS = os.path.join(_REPO_ROOT, "simulator", "helpers", "ardupilot")
_codegen_path = os.path.join(_REPO_ROOT, "simulator", "helpers", "codegen.py")
_spec = importlib.util.spec_from_file_location("codegen", _codegen_path)
assert _spec is not None and _spec.loader is not None
_codegen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_codegen)  # type: ignore[union-attr]
make_docstring = _codegen.make_docstring
write_init_file = _codegen.write_init_file


def _existing_enum_names(enums_dir: str) -> list[str]:
    """Parse class names from enums/__init__.py without importing the module."""
    init_path = os.path.join(enums_dir, "__init__.py")
    if not os.path.exists(init_path):
        return []
    with open(init_path) as f:
        return re.findall(r"^from \.\w+ import (\w+)", f.read(), re.MULTILINE)
PARAM_PATH = os.path.join(_ARDUPILOT_HELPERS, "ardupilot.pdef.json")
_PDEF_REL = os.path.relpath(PARAM_PATH, _REPO_ROOT)

manual_imports: list[
    str
] = []  # Add any manually written enums to be included in __init__.py

with open(PARAM_PATH) as f:
    param_data = json.load(f)

PARAM_DEFS = [
    {
        "component": "Copter",
        "name": "FrameClass",
        "param": "FRAME_CLASS",
    },
    {
        "component": "Copter",
        "name": "FrameType",
        "param": "FRAME_TYPE",
    },
    {
        "component": "BRD_",
        "name": "BRDType",
        "param": "BRD_TYPE",
    },
    {
        "component": "MOT_",
        "name": "MOTPWMType",
        "param": "MOT_PWM_TYPE",
    },
]


def sanitize_identifier(name: str) -> str:
    """Sanitize a string to be a valid Python identifier."""
    sanitized = re.sub(r"\W|^(?=\d)", "_", name)
    return sanitized if sanitized.isidentifier() else f"_{sanitized}"


def generate_int_enum(enum_name: str, values: dict[str, str], description: str) -> str:
    """
    Generate the source code string for an IntEnum
    class based on parameter values.
    """
    lines = [
        f"{make_docstring(description, indent=0)}",
        "",
        "from enum import IntEnum",
        "",
        "",
        f"class {enum_name}(IntEnum):",
        make_docstring(
            description + f"\nAutogenerated from {_PDEF_REL}.",
            indent=4,
        ),
        "",
    ]
    for k, v in values.items():
        try:
            val = int(k)
        except ValueError:
            continue
        name = sanitize_identifier(v)
        lines.append(f"    {name} = {val}")
    return "\n".join(lines) + "\n"


def write_int_enum_file(
    name: str, values: dict[str, str], outfile: str, description: str
):
    """Write an IntEnum class to the specified output file."""
    code = generate_int_enum(name, values, description)
    os.makedirs(os.path.dirname(outfile), exist_ok=True)
    with open(outfile, "w") as f:
        f.write(code)
    print(f"\u2705 IntEnum written to {outfile}")


if __name__ == "__main__":
    ENUM_DIR = os.path.join(_ARDUPILOT_HELPERS, "enums")
    for param in PARAM_DEFS:
        enum_name = param["name"]
        outfile = os.path.join(ENUM_DIR, f"{enum_name.lower()}.py")
        values = param_data[param["component"]][param["param"]]["Values"]
        description = param_data[param["component"]][param["param"]]["Description"]
        write_int_enum_file(enum_name, values, outfile, description)

    generated = [p["name"] for p in PARAM_DEFS]
    write_init_file(ENUM_DIR, generated + _existing_enum_names(ENUM_DIR))
