"""Autogenerated. ArduPlane airspeed parameters."""

from __future__ import annotations

from enum import Enum


class AirSpeed(bytes, Enum):
    """
    Autogenerated. Autogenerated from `Plane` entries starting with
    `AIRSPEED_` in simulator/helpers/ardupilot/ardupilot.pdef.json.
    """

    CRUISE = b"AIRSPEED_CRUISE"
    MAX = b"AIRSPEED_MAX"
    MIN = b"AIRSPEED_MIN"
    STALL = b"AIRSPEED_STALL"
