"""
Autogenerated. This allows selection of a PX4 or VRBRAIN board type. If set to
zero then the board type is auto-detected (PX4).
"""

from __future__ import annotations

from enum import IntEnum


class BRDType(IntEnum):
    """
    Autogenerated. This allows selection of a PX4 or VRBRAIN board type. If
    set to zero then the board type is auto-detected (PX4) Autogenerated
    from simulator/helpers/ardupilot/ardupilot.pdef.json.
    """

    AUTO = 0
    PX4V1 = 1
    PX4_OLDDRIVERS = 100
    Intel_Aero_FC = 13
    Pixhawk_Pro = 14
    Pixhawk = 2
    AUAV2_1 = 20
    PCNC1 = 21
    MINDPXV2 = 22
    SP01 = 23
    CUAVv5_FMUV5 = 24
    Cube_Pixhawk2 = 3
    VRX_BRAIN51 = 30
    VRX_BRAIN52 = 32
    VRX_BRAIN52E = 33
    VRX_UBRAIN51 = 34
    VRX_UBRAIN52 = 35
    VRX_CORE10 = 36
    VRX_BRAIN54 = 38
    PX4_FMUV6 = 39
    Pixracer = 4
    PixhawkMini = 5
    Pixhawk2Slim = 6
